version: '3.8'
services:
  db:
    container_name: mydb
    image: mysql:5-oracle
    restart: always
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3305:3306'
  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8070:8080
  phpmyadmin:
    image: phpmyadmin:5.2.0
    environment:
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "9090:8080"
      - "91:80"


# Names our volume
volumes:
  mysql: